apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: k0hzqxg2x-go
  janus-idp.io/tekton: k0hzqxg2x-go
  backstage.io/kubernetes-id: k0hzqxg2x-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: k0hzqxg2x-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
